### ISSUE TITLE
Failed to getValue() with method com.codepine.api.testrail.model.Result#getCustomFields(0 params): null (through reference chain: com.codepine.api.testrail.model.Result["[anySetter]"])

### ISSUE THREAD

**Issue by marcmyers** [codepine/testrail-api-java-client#14]
I've been banging my head on this for about a week straight now and can't figure out why this is happening.

I'm using the latest stable version of the testrail-api-java (1.0.1) in a mavenized java 1.8 project with the latest Selenium and TestNG.

I'm attempting to update a test run with the results of a test using the following code:
```
List<ResultField> customResultField = testRail.resultFields().list().execute();
testRail.results().addForCase(testRun.getId(), testId, new Result().setStatusId(testStatus), customResultField).execute();
```

The update was failing with a RuntimeException: 
```
com.fasterxml.jackson.databind.JsonMappingException: Failed to getValue() with method com.codepine.api.testrail.model.Result#getCustomFields(0 params): null (through reference chain: com.codepine.api.testrail.model.Result["[anySetter]"])
```

My java knowledge is prob novice at best as I'm self taught so I apologize if this is obvious and not an actual issue with this library.

Any help would be greatly appreciated as I've tried literally everything I can think of.

UPDATE: I updated my pom to refer to version 1.0.2 in case I was mistaken about which version was stable and the exception still occurs.

UPDATE: A java developer I know suggested adding Lombok to my classpath, the exception still occurs regardless.

**Comment by jaymagpantay** [comment]
I am getting the same error. Any help would be appreciated.

**Comment by jaymagpantay** [comment]
So I think I figured out the problem:

The issue is with the Result.getCustomFields method, which is defined as
```
public Map<String, Object> getCustomFields() {
        return Objects.firstNonNull(customFields, Collections.<String, Object>emptyMap());
    }
```
I looked up Objects.firstNonNull and found that this was part of Guava. In the docs for Guava 20.0 (http://google.github.io/guava/releases/20.0/api/docs/com/google/common/base/Objects.html#firstNonNull-T-T-), I found this interesting tidbit:

> @Deprecated
public static <T> T firstNonNull(@Nullable
                                             T first,
                                             @Nullable
                                             T second)
Deprecated. Use MoreObjects.firstNonNull(T, T) instead. **This method is scheduled for removal in Guava 21.0.**

So, looking at my project's other dependencies, I found that one of them had upgraded to Guava 21.0, thus causing this issue. I forced Guava 20.0 by adding the dependency to my pom file, and I am not getting the issue anymore. 

The testrail-api-java-client is currently on 16.0.1. It would be great if it was upgraded to a newer version and fixed to not use Objects.firstNonNull.

**Comment by jaymagpantay** [comment]
@kunal546 Would it be possible for you to update getCustomFields to  use MoreObjects.firstNonNull? Thank you.

**Comment by chelyuk** [comment]
Hi guys, could you please update to latest version in maven repository, please. This issue is really "show stopper" for me to use api-client. Because version in maven still depends on guava 16.0.1 but all Selenium Drivers already depends on guava 21. So, it is impossible to use the in api-client in projects with Selenium testing. If I can help in any way I would be pleased.

**Comment by welnanick** [comment]
I am running into the exact same issue using appium (which in turn uses selenium), and do not have the option to force Guava < 21.0. @kunal546 please release an update. This library is currently incompatible with anything that uses guava 21.0 or higher.

**Comment by adchaos** [comment]
@kunal546 same issue here :)

**Comment by kunal546** [comment]
Sorry for the delay. v2.0.0 has been released which addresses this.
