### ISSUE TITLE
operate on Collections rather than Lists

### ISSUE THREAD

**Issue by alexeyOnGitHub** [codepine/testrail-api-java-client#4]
Hi! I see this API:

        client.results().add(runId, results, customResultFields).execute();

results has to be a List. why not just Collection?..

**Comment by kunal546** [comment]
Since List extends from Collection:
- it allows for some more operations compared to the Collection.
- caller still has the option of using reference type Collection if not interested in List operations but it could not have happened the other way around without checking the implementation type explicitly.

Besides having the flexibility to change the implementation in future for e.g. to Set or Queue, I don't see any reason for having a Collection. I think List implementation fits well.

Is there any reason why you would want Collection which I may be missing?

**Comment by alexeyOnGitHub** [comment]
well, I had some Collections in my app and I was surprised to see that the API expects Lists rather than more generic collections. 
a List indicates that elements are (at least supposed to be) ordered elements: you can traverse them in a certain order. if ordering is NOT important for the API (and I think it is not), then IMHO it should accept Collections instead and then traverse them through iterators or whatever.

same with returning elements from the API back to client code: if there is no guaranteed ordering (elements are returned in some random order), then Lists can be misleading.

if clients need to perform any operations on a collection that they want to treat as list, then IMHO they should just create a new list for their needs..

just IMHO :)
it's up to you.
I was just surprised by this requirement that I needed to provide List of Results rather than "some Results".

**Comment by kunal546** [comment]
I agree that expecting Collection would have made better APIs since ordering is not important. For returning elements, the intention was to maintain (and guarantee) the element order present in the service response.

The List properties in models cannot be changed now else it'll break backwards compatibility. But in general, I don't see this as a blocking/critical issue so I'll mark this as "won't fix". Please let me know if you feel otherwise and would like to see a few specific APIs fixed which do not break backwards compatibility. And feel free to submit a patch :)

**Comment by alexeyOnGitHub** [comment]
well, I'll just create a new immutable list each time I need to call the API.
